### ISSUE TITLE
Template Peakdetector constructs invalid Peaks

### ISSUE THREAD

**Issue by laeubi** [OpenChrom/openchrom#30]
Applying the TPD to a file I see a lots of  the following messages in the log:
WARN  ModalContext support.PeakSupport.extractPeakByScanRange (PeakSupport.java:111) org.eclipse.chemclipse.model.exceptions.PeakException: There must be at least one intensity value stored with a relative intensity of IPeakIntensityValues.MAX_INTENSITY.

**Comment by Mailaender** [comment]
I saw those error messages too when I added invalid peak ranges at https://github.com/eclipse/chemclipse/pull/608 which turned out to be a mistake in the parser from my side, so I think you may be feeding invalid data as well. Feel free to re-open with a test case attached if you think this is a problem in general. Invalid peaks are discarded by default.
