### ISSUE TITLE
Template PeakIdentifier: merging of peaks with the same name

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#55]
Creating the template's .txt by "save as", the Template PeakIdentifier merges adjacent peaks with the same name. This I do not expect and I can not find any settings on this in the settings. 
Why is not every peak from peak/scan list exported? 
On which parameters the merge is based and can they be modified by the user, or turned off?

**Comment by danield5732** [comment]
Maybe a correction: The peaks are not merged but lines are lost, if the actual name already exists.
This may be linked to #48

**Comment by Mailaender** [comment]
My test case is as follows: open the demo chromatogram. Replace targets with unknown markers (no m/z) for adjacent peaks

![image](https://user-images.githubusercontent.com/756669/112186992-f2b90600-8c01-11eb-9ce5-419e76d2fed5.png)

The report contains the expected number of peaks included the unknowns:

```
40.366 | 40.560 | Adipic acid, isohexyl pent-4-en-2-yl ester | 0-00-0 |  |  |  | 129,111 | 
41.644 | 41.928 | Adipic acid, decyl pent-4-en-2-yl ester | 0-00-0 |  |  |  | 129,215 | 
43.219 | 43.361 | Unknown [] |  |  |  |  | 105,77 | 
44.601 | 44.756 | Unknown [] |  |  |  |  | 149,105 | 
45.143 | 45.233 | Unknown [] |  |  |  |  | 108,109 | 
45.233 | 45.388 | Unknown [] |  |  |  |  | 149,233 | 
```

This may already be fixed in the latest version or could be a specific problem that only appears with your data.
