### ISSUE TITLE
Peak/Scan List - sorting issue for Name and Classifier columns

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#77]
There seems to be a sorting issue for the Peak/Scan List.
While Numbers are sorted correctly the Classifier column ist sorted weird.
![Screenshot from 2020-08-05 14-11-39](https://user-images.githubusercontent.com/19611569/89411499-ceb5bc80-d725-11ea-9675-61520de44140.png)

For the Name column sorting is case-sensitive but it shouldn't. This is less intuitive since it leads to: 1...9 A...Z a....z
![Screenshot from 2020-08-05 14-14-45](https://user-images.githubusercontent.com/19611569/89412111-cdd15a80-d726-11ea-98de-b137605a5361.png)

**Comment by eselmeister** [comment]
@danield5732 Thanks for reporting. I'll have a look at it.

**Comment by eselmeister** [comment]
@danield5732 Thanks for your report. This is fixed in the next version.
https://github.com/eclipse/chemclipse/issues/415

![Bildschirmfoto von 2020-09-11 11-35-40](https://user-images.githubusercontent.com/686671/92905523-02ba8680-f424-11ea-9a51-21c1102a3d43.png)

![Bildschirmfoto von 2020-09-11 11-36-33](https://user-images.githubusercontent.com/686671/92905535-06e6a400-f424-11ea-8f5d-941abdf2d8ed.png)
